{% set name = "librdkafka" %}
{% set version = "0.11.4-RC3" %}
{% set sha256 = "ef3861ba4d9863fed855c58ddad27520fb74ab90b46377653ecf7b988be66211" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/edenhill/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - toolchain  # [unix]
    - zlib 1.2.*
    - openssl 1.0.*
    - libgsasl  # [not osx]
    - lz4-c
  run:
    - zlib 1.2.*
    - openssl 1.0.*
    - libgsasl  # [not osx]
    - lz4-c

test:
  commands:
    - test -f ${PREFIX}/lib/librdkafka.so  # [linux]
    - test -f ${PREFIX}/lib/librdkafka++.so  # [linux]
    - test -f ${PREFIX}/lib/librdkafka.dylib  # [osx]
    - test -f ${PREFIX}/lib/librdkafka++.dylib  # [osx]

    - conda inspect linkages {{ name }}  # [unix]
    - conda inspect objects {{ name }}   # [osx]

about:
  home: https://github.com/edenhill/librdkafka
  license: BSD 2-clause
  license_family: BSD
  license_file: LICENSE
  summary: 'The Apache Kafka C/C++ client library'
  description: |
    librdkafka is a C library implementation of the Apache Kafka protocol,
    containing both Producer and Consumer support. It was designed with message
    delivery reliability and high performance in mind, current figures exceed 1
    million msgs/second for the producer and 3 million msgs/second for the
    consumer.

extra:
  recipe-maintainers:
    - kwilcox
