{% set name = "librdkafka" %}
{% set version = "0.11.6-PRE1" %}
{% set sha256 = "8a235f6fd5663cfbf6bc6bd9f5b0cb73d2d4bbe7f43ad41bacfa343c547dda59" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/edenhill/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - zlib
    - openssl
    - libgsasl  # [not osx]
    - lz4-c
  run:
    - zlib
    - openssl
    - libgsasl  # [not osx]
    - lz4-c

test:
  commands:
    - test -f ${PREFIX}/lib/librdkafka${SHLIB_EXT}  # [not win]
    - test -f ${PREFIX}/lib/librdkafka++${SHLIB_EXT}  # [not win]

    - conda inspect linkages {{ name }}  # [unix]
    - conda inspect objects {{ name }}   # [osx]

about:
  home: https://github.com/edenhill/librdkafka
  license: BSD 2-clause
  license_family: BSD
  license_file: LICENSE
  summary: 'The Apache Kafka C/C++ client library'
  description: |
    librdkafka is a C library implementation of the Apache Kafka protocol,
    containing both Producer and Consumer support. It was designed with message
    delivery reliability and high performance in mind, current figures exceed 1
    million msgs/second for the producer and 3 million msgs/second for the
    consumer.

extra:
  recipe-maintainers:
    - kwilcox
