appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: LnoSkixUdTwVSJU94VBhtc4ydZMsCbsKGXY0ASMYOvx0PZBRkkaZOR1SMtRB36bb7kwxdO70tKJjcsK24ww3DsDS/wdu637jwfd7DWh7zHlNTaWZLCyn2ULiVDHDYyL+dOFB9JE6EbvXlWSRS50+aTlRpViGxgPUdHWVbeRKvVW3F/Kb66hK8rToMhlUFaDnO42GILuQO/7pbzy0ZrbexrhhQVPlkNw34peBM/eRRjA9PGcZsLH1H8tvgo5ZNJFWfkh9bFM5hfBTpJ1vrEdtiEzn5vZTiXFh2FtW4ggRJOUd+K2OnJljvNm9dQO9+2M3FURtK5AlDXnhjXEiLnEoO6O4yu3UeMlEUGQWe+fBhGOuRSNeSWzvQJSAcLuSWZ26NP4nwusPOdvV/zMUm1NHnbIdQwjbi3gaHCyWflVnwqvrwN6UYBSsPZ2kx0nC2sQdt2osTxO0sjW+ykpS3rmU0bfseCopmROwVDMUI23z0CAP92yHJdpXchrmS0/YlPF8S0ewQMnMiPQP0cj7rMf5DfgTvkNAKVeHRIavporVmBZEKhDL8q/6/neVHb4BDfy7YK2TBpPahUlP3zjs5yvgG/yVGl64/mpkZ3hknIlksZ8u9FijRSXcLLIyQww4qvWytzryocX/og7oJ/ANmKI6GlaI7WFT1r79qZUMHdsuxBc=}
